# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-19 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20180216_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.IntegerField(choices=[(0, 'Blocked'), (1, 'Active'), (2, 'Pending')], default=0),
        ),
    ]
