# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-19 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20180219_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_of_birthday',
            field=models.DateTimeField(verbose_name='date of birthday'),
        ),
    ]
