# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-20 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20180220_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_of_birthday',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date of birthday'),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=6, null=True),
        ),
    ]
