# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-22 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20180221_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(default='default.png', upload_to='category/'),
        ),
    ]
