# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-23 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20180222_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='company',
            field=models.OneToOneField(default=9, on_delete=django.db.models.deletion.CASCADE, to='users.Company'),
        ),
    ]
