# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-06 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_review_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
