# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-10 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAvatars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to='users/%y/%m/%d')),
            ],
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, default='default.png', null=True, upload_to='album/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserAvatars'),
        ),
    ]
