# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-11 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_auto_20180311_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useravatars',
            old_name='avatar',
            new_name='user',
        ),
    ]
