# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-12 13:45
from __future__ import unicode_literals

from django.db import migrations
import geosimple.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20180311_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='position',
            field=geosimple.fields.GeohashField(db_index=True, default={'latitude': 50.822482, 'longitude': -0.141449}, max_length=12),
        ),
    ]
