# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-12 18:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_auto_20180312_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=0)),
                ('like_dislike_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_like_dislike_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
