# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-12 18:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_reviewlikes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewLikes',
            new_name='ReviewLikeDislike',
        ),
    ]
