# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-12 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_auto_20180312_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewlikedislike',
            name='review',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='users.Review'),
            preserve_default=False,
        ),
    ]
