# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-15 09:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='notification_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
