# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-17 12:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_auto_20180317_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companypromotion',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companypromotion',
            name='promotion_type',
        ),
        migrations.RemoveField(
            model_name='notificationpromotion',
            name='company',
        ),
        migrations.DeleteModel(
            name='CompanyPromotion',
        ),
        migrations.DeleteModel(
            name='NotificationPromotion',
        ),
        migrations.DeleteModel(
            name='PromotionType',
        ),
    ]
