# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-21 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_auto_20180317_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=15, unique=True)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='closing_time',
        ),
        migrations.RemoveField(
            model_name='company',
            name='opening_time',
        ),
        migrations.AddField(
            model_name='weektime',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Company'),
        ),
    ]
