# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-21 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_auto_20180321_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weektime',
            name='day',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=15),
        ),
    ]
