# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-31 05:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_weektime_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='created_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, default=datetime.datetime(2018, 3, 31, 5, 45, 13, 729974, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
