# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-03 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_notifications_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='svg_icon',
            field=models.FileField(default='default.png', upload_to='category/'),
        ),
    ]
