# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-21 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_auto_20180420_1154'),
        ('users', '0055_auto_20180420_1145'),
    ]

    operations = [
    ]
