# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-12 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaycomTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paycom_transaction_id', models.CharField(max_length=255, unique=True)),
                ('paycom_time', models.CharField(max_length=15)),
                ('paycom_time_datetime', models.DateTimeField()),
                ('create_time', models.DateTimeField()),
                ('perform_time', models.DateTimeField(blank=True, null=True)),
                ('cancel_time', models.DateTimeField(blank=True, null=True)),
                ('amount', models.CharField(max_length=50)),
                ('state', models.IntegerField()),
                ('reason', models.IntegerField(blank=True, null=True)),
                ('receivers', models.TextField(blank=True, null=True)),
                ('promotion_id', models.PositiveIntegerField()),
                ('promotion_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
