# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-12 09:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(blank=True, choices=[('0', 'Available'), ('1', 'Awaiting Payment'), ('2', 'Payment completed'), ('3', 'Cancelled')], default='0', max_length=20)),
                ('promotion_id', models.PositiveIntegerField()),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('promotion_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.RemoveField(
            model_name='paycomtransaction',
            name='promotion_id',
        ),
        migrations.RemoveField(
            model_name='paycomtransaction',
            name='promotion_type',
        ),
        migrations.AddField(
            model_name='paycomtransaction',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.Order'),
        ),
    ]
