# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-21 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotiontype',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Uzs', max_digits=10),
        ),
    ]
