# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-31 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0002_auto_20180321_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotiontype',
            name='action_type',
            field=models.CharField(choices=[('click', 'Per click'), ('view', 'Per view'), ('notification', 'Per notification')], max_length=12, unique=True),
        ),
    ]
