# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-01 12:46
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0005_auto_20180401_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotiontype',
            name='action_type',
        ),
        migrations.RemoveField(
            model_name='promotiontype',
            name='price',
        ),
        migrations.AddField(
            model_name='promotiontype',
            name='click_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Uzs', max_digits=10),
        ),
        migrations.AddField(
            model_name='promotiontype',
            name='view_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Uzs', max_digits=10),
        ),
        migrations.AlterField(
            model_name='promotiontype',
            name='promote_type',
            field=models.CharField(choices=[('show_in_search', 'Show in search'), ('show_in_related', 'Show in related')], default='', max_length=40),
        ),
    ]
